name: whisper
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

scripts:
  gen:
    flags: dart lib/core/gen_flags.dart

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartx: ^1.2.0
  # flame: ^1.15.0
  logger: ^2.2.0
  stack_trace: ^1.11.1
  bonfire: ^3.6.2
  typewritertext: ^3.0.8
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3

dependency_overrides:
  bonfire:
    path: ../bonfire

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tilesets/
