import 'package:whisper/core/core.dart';

const Map<MentalTrait, List<String>> soulWhispersByTrait = {
  MentalTrait.greedy: [
    "You are the chosen one",
    "You need more",
    "All your life you've beeen sacrificing for others",
    "You deserve more",
    "It could all be yours",
    "Why settle for less",
    "Let them witness your splendor",
    "Bodies decompose, gold is forever",
  ],
  MentalTrait.fanatic: [
    "Faith demands sacrifice",
    "Burn them in the stakes",
    "God is mighty",
    "You are acting through God",
    "We must fight for what we believe",
    "Only one way is right",
    "Who would dare oppose us",
    "Ours is the way",
    "You have the divine right",
  ],
  MentalTrait.doubtful: [
    "He's not listening",
    "We are all alone",
    "The silence is deafening",
    "We have been decieved",
    "It's too good to be true",
    "Stop hiding from the Truth",
    "Listen carefully...",
    "It's cold, so cold",
    "He's dead",
  ],
  MentalTrait.zealous: [
    "You are the chosen one",
    "You must save them",
    "The kingdom needs you",
    "Save us!",
    "The righteous will be victorious",
    "You are the hand of Justice",
    "Evil triumphs when Good remains idle",
    "You must keep the Devil away",
    "Carve your name in history oh great Champion",
  ],
  MentalTrait.superstitious: [
    "Demons are within us",
    "The crows are flying, a bad omen",
    "Beware the undead",
    "Do you hear them howl at night?",
    "Spirits of the victims of war haunt the village",
    "Rumours are that the Priest is actually a Necromancer",
    "The village beyond the mountains was consumed by undeath",
    "There will be a Full Moon tonight",
    "It is said that at night, whispers can be heard on the graveyeards",
    "The great beyond calls your name",
  ],
  MentalTrait.paranoid: [
    "They are watching you",
    "They lie to you",
    "A bunch of rats, they are",
    "Beware",
    "Evil lurks nearby",
    "The villagers are acting strange",
    "Death is in the air",
    "You are in danger",
    "Nothing is as it seems",
    "They are plotting against you",
  ],
};
